# Scheduled workflow

name: cron

on:
  issues:
    types: [ opened, reopened ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        env:
          # Stupid Github doesn't allow triggering recursive workflows with the ephemeral automatic token
          ACTIONS_TOKEN: ${{ secrets.PAT }}
        run: |
          auth="Authorization: token $ACTIONS_TOKEN"
          repo="FriendlyNeighborhoodShane/MinMicroG-abuse-CI"
          flow="run.yml"
          data='{ "ref": "hub" }'
          apie="https://api.github.com/repos/$repo/actions/workflows/$flow/dispatches"
          curl -H "$auth" --data "$data" "$apie"
